/**
 * 数字人壁纸 - 导出脚本
 * 
 * 生成 Wallpaper Engine 可直接导入的静态资源包
 */

import { execSync } from 'child_process';
import { existsSync, mkdirSync, writeFileSync, readFileSync, copyFileSync, rmSync, readdirSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

console.log('🏗️  开始导出数字人壁纸...\n');

// 1. 构建前端
console.log('📦 构建前端...');
execSync('npm run build', { cwd: rootDir, stdio: 'inherit' });

// 2. 创建导出目录
const exportDir = join(rootDir, 'export');
const distDir = join(rootDir, 'dist');

if (existsSync(exportDir)) {
  rmSync(exportDir, { recursive: true });
}
mkdirSync(exportDir);

// 3. 复制构建产物
console.log('📁 复制静态文件...');
copyFileSync(join(distDir, 'index.html'), join(exportDir, 'index.html'));

// 复制 assets
const srcAssets = join(distDir, 'assets');
if (existsSync(srcAssets)) {
  copyDir(srcAssets, join(exportDir, 'assets'));
}

// 4. 创建 Wallpaper Engine 配置
console.log('⚙️  生成 Wallpaper Engine 配置...');
const projectJson = {
  "name": "数字人壁纸",
  "author": "Digital Wallpaper Team", 
  "version": "1.0.0",
  "description": "数字人团队状态展示与虚拟办公场景",
  "site": "https://github.com/MMXC/digital-wallpaper",
  "worksWith": ["kr.stealth.scenamatica"],
  "properties": {
    "schemaversion": 3,
    "type": "weball",
    "url": "index.html",
    "fullscreen": true,
    "volume": 100,
    "random": false,
    "priority": 1,
    "supportsMonitoring": true,
    "supportsDeepLinking": false
  },
  "file": "index.html",
  "tags": ["Abstract", "3D", "Interactive"],
  "compatVersion": "latest"
};

writeFileSync(join(exportDir, 'project.json'), JSON.stringify(projectJson, null, 2));

// 5. 创建说明文件
const readme = `# 数字人壁纸

## 安装方式

1. 下载 release 包
2. 解压
3. 打开 Wallpaper Engine
4. 选择"从文件创建壁纸"
5. 选择解压后的文件夹

## 功能

- 3D 虚拟办公场景
- 数字人状态展示
- 任务看板
- 天空盒切换

---
Generated by digital-wallpaper
`;

writeFileSync(join(exportDir, 'README.md'), readme);

// 6. 打包成 zip (使用系统 zip 命令)
console.log('📦 打包...');
const zipPath = join(rootDir, 'digital-wallpaper.zip');

// 删除旧包
if (existsSync(zipPath)) {
  rmSync(zipPath);
}

// 使用系统 zip 命令
try {
  execSync(`cd "${exportDir}" && zip -r "${zipPath}" .`, { stdio: 'inherit' });
} catch (e) {
  // Windows 可能没有 zip，尝试用 PowerShell
  console.log('⚠️  系统无 zip 命令，尝试使用 PowerShell...');
  execSync(`Compress-Archive -Path "${exportDir}/*" -DestinationPath "${zipPath}" -Force`, { stdio: 'inherit' });
}

console.log(`\n✅ 导出完成!`);
📦 产物:console.log(` ${zipPath}`);

function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry);
    const destPath = join(dest, entry);
    if (statSync(srcPath).isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}
